# Generated by Django 2.0.6 on 2018-06-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180606_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['article_id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='path',
        ),
    ]
